[package]
name = "packet-capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.23.1"
log = "0.4"
env_logger = "0.6.1"

[build-dependencies]
pnet_macros = "0.20.0"
